package com.android.safepay.network.utils

object TrackerStatus
{
    const val TRACKER_STARTED = "TRACKER_STARTED"
    const val TRACKER_AUTHORIZED = "TRACKER_AUTHORIZED"
    const val TRACKER_ENROLLED = "TRACKER_ENROLLED"
    const val TRACKER_ENDED = "TRACKER_ENDED"
    const val TRACKER_CANCELLED = "TRACKER_CANCELLED"
    const val TRACKER_EXPIRED = "TRACKER_EXPIRED"
    const val TRACKER_REFUNDED = "TRACKER_REFUNDED"
    const val TRACKER_PARTIAL_REFUND = "TRACKER_PARTIAL_REFUND"
    const val TRACKER_DISPUTED = "TRACKER_DISPUTED"
    const val TRACKER_REVERSED = "TRACKER_REVERSED"
    const val TRACKER_VOIDED = "TRACKER_VOIDED"
}